name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: latest
        env:
            DOCKER_USERNAME: ${{ dumitrualex252000 }}
            DOCKER_PASSWORD: ${{ dckr_pat_trxdJgXvPb_LyPefdX9lX9yU6Ak }}
